export ARDUINO_LIBS = Wire SparkFunBQ27441
export USER_LIB_PATH=../libraries
export AVRDUDE_ARD_BAUDRATE = 57600
export BOARD_TAG = pro328
#/usr/share/arduino/libraries

include /usr/share/arduino/Arduino.mk
